Extend env variables to fix literal string parsing
drone-plugins/drone-meltwater-cache pull request #62
Opened 2023-11-15 18:25 UTC by Aishwarya-Lad

Please read [CONTRIBUTING.md](CONTRIBUTING.md) for details on our [code of conduct](CODE_OF_CONDUCT.md), and the process for submitting pull requests to us.

Fixes #

## Proposed Changes

-
-
-

### Description
Env variables are not getting parsed correctly when passed on to the cache plugin. 

Extended the env variables before setting the cache directory
### Checklist

- [x] Read the [**CONTRIBUTING**](CONTRIBUTING.md) document.
- [x] Read the [**CODE OF CONDUCT**](CODE_OF_CONDUCT.md) document.
- [ ] Add tests to cover changes.
- [x] Ensure your code follows the code style of this project.
- [ ] Ensure CI and all other PR checks are green OR
    - [x] Code compiles correctly.
    - [ ] Created tests which fail without the change (if possible).
    - [ ] All new and existing tests passed.
- [ ] Add your changes to `Unreleased` section of [CHANGELOG](CHANGELOG.md).
- [ ] Improve and update the [README](README.md) (if necessary).
- [ ] Ensure [documentation](./DOCS.md) is up-to-date. The same file will be updated in [plugin index](https://github.com/drone/drone-plugin-index/blob/master/content/meltwater/drone-cache/index.md) when your PR is accepted, so it will be available for end-users at http://plugins.drone.io.

2023-11-15 18:58 UTC, jamie-harness requested changes

2023-11-15 18:58 UTC, jamie-harness commented on archive/tar/tar.go
> +	    src = os.ExpandEnv(src)
change this in restorer.go instead of here. We should have it in upstream already

2023-11-15 19:58 UTC, Aishwarya-Lad commented on archive/tar/tar.go
> +	    src = os.ExpandEnv(src)
Done

2023-11-17 04:59 UTC, hemanthmantri commented on cache/rebuilder.go
> +		level.Info(r.logger).Log("msg", "os.ExpandEnv($HOME)", "test", os.ExpandEnv("$HOME"))
These should be debug level IMHO. Alternatively, we can consider printing one log line as follows:
"Source %s is resolved to %s"

2023-11-17 04:59 UTC, hemanthmantri commented on cache/rebuilder.go
> -
Do we know why are we removing this?

2023-11-17 04:59 UTC, hemanthmantri commented on cache/restorer.go
> +        level.Info(r.logger).Log("srcs", "After expansion ", src)
Consider just one log line as mentioned above.

2023-11-17 06:36 UTC, closed without merging